### ISSUE TITLE
求教一个问题，如何能按行处理一个文件，并且能支持空行？

### ISSUE THREAD

**Issue by andares** [goreliu/zshguide#11]
我的思路是要么读入整体文件转为数组```array=(${(f)"$(<test.txt)"})```，要么用```while {read line}```逐行读取。

但遇到空行都会忽略。我猜测是(f)转换时就会跳过空行，而while方案也会有一样的问题（可能是read返回值问题交给while判断出错，或者read本身就是忽略空行的）。导致单纯通过zsh做逐行处理还原一个文件成了不可能的任务（不想用sed这些指令）。

为此我还试了read的各种参数，搞了整整一个下午，有种条条大路是死路的感觉。。

求教大佬有没有什么方法能在纯shell脚本中解决这类问题？

**Comment by goreliu** [comment]
```
% cat a.txt
a
b

c


d
% while {read a} {echo $a} < a.txt
a
b

c


d
```

**Comment by andares** [comment]
单这么跑直接echo是好的，但那天测试就是不行。如果问题不是出在读上，那么就出在写上。目前这个问题是一直存在的，现在我的项目[Yup](https://github.com/veeshan-io/yup)在写入```.zshrc```时用的sed指令，但在生成```.yuprc```的时候用的```while {read line}```仍然会丢掉空行。

我用的思路比较偏向普通的程序开发，从shell脚本的角度上来看会有些封装过度。

```bash
view.render() {
    if [[ ! -e $1 ]] {
        echo "Template $1 is not exists."
        return 1
    }
    if [[ -d $1 ]] {
        echo "Template $1 must be a file."
        return 1
    }

    local -A vars=($*[2,-1])
    IFS_bak=$IFS
    IFS="\n"
    while {read line} {
        for k v (${(kv)vars}) {
            line=(${line//"{{$k}}"/$v})
        }
        echo $line
    } <$1
    IFS=$IFS_bak
}


file.insert_before() {
    IFS_bak=$IFS
    IFS="\n"
    while {read line} {
        if (($line[(I)$2])) {
            for insert ($*[3,-1]) {
                echo $insert
            }
        }

        echo $line
    } <$1
    IFS=$IFS_bak
}

file.write() {
    local target=$1
    local content=$2

    >$target < /dev/null
    for line (${(f)content}) {
        echo -ne "$line\n" >>$target
    }
}
```

相关的函数有上面几个，第一个起到类似模版作用，实际上在和```file.write```配合时和第二个思路是一样的，都是echo出来后转另一个字串再写进文件。

```bash
local insert=(
  "\n"
  'source ~/.yuprc'
  "\n"
 )
file.write ~/.zshrc "$(file.insert_before ~/.zshrc ZSH/oh-my-zsh.sh $insert)"
```

上面这句是安装脚本中当前被注释掉的部分（现使用sed代替），要么就是```"$()"```这种获取返回值再写入的模式存在问题。```file.write```函数中的```echo -ne```中的```-ne```和```\n```是后来调试时加入的，最早就是简单的```echo $line >>$target```

**Comment by goreliu** [comment]
希望能提炼出更简单直接的例子。另外 zsh 里一般不需要改 IFS。

**Comment by goreliu** [comment]
```
file.write() {
    local target=$1
    local content=$2

    >$target < /dev/null
    for line (${(f)content}) {
        echo -ne "$line\n" >>$target
    }
```

这里 `for line (${(f)content}) {` 会丢失空行，可以这样：

`for line (${(s:\n:)content}) {`

**Comment by andares** [comment]
> 
> 
> ```
> file.write() {
>     local target=$1
>     local content=$2
> 
>     >$target < /dev/null
>     for line (${(f)content}) {
>         echo -ne "$line\n" >>$target
>     }
> ```
> 
> 这里 `for line (${(f)content}) {` 会丢失空行，可以这样：
> 
> `for line (${(s:\n:)content}) {`

感谢，有空试一下。现在正在转向fish 😂
