### ISSUE TITLE
第一章,always语句测试与预期不符

### ISSUE THREAD

**Issue by royaso** [goreliu/zshguide#13]
异常处理语句

# 格式
{
    语句 1
} always {
    语句 2
}

如果语句 1 执行出错，则执行语句 2。

---------
```
{ 
true
} always{
echo yyy
}


{ 
false
} always{
echo yyy
}
```
结果都是会输出yyy

**Comment by tztnuaji** [comment]
同样的问题，建议使用：
{command} && 
这种方式判断

**Comment by goreliu** [comment]
已修改（ https://github.com/goreliu/zshguide/commit/ec43f552c3f9d46a4fd9c16c54f658c33b7f3ade ）。
